ur_gym: #namespace
    # General Agent parameters
    env_id: "UR3eJointSpaceEnv-v0"
    driver: "gazebo" # or "robot" or "old_driver"
    ft_sensor: False
    relative_to_ee: False
    agent_control_dt: 0.05
    reset_time: 1.0

    steps_per_episode: 100
    
    rand_seed: 10   
    # initial conditions
    random_initial_pose: False
    rand_init_interval: 1
    # for each dimension define upper and lower bound from initial pose
    workspace: [[0.04,-0.04], [0.04, -0.04], [0.005, 0.02], [10, -10], [10, -10], [10, -10]]
    init_q: [1.57, -1.57, 1.26, -1.57, -1.57, 0.0]

    target_pose_uncertain: False
    uncertainty_std: [0.001, 0.0]
    target_pos: [-0.19892, 0.29468, 0.04454, 0.9971, -0.00037, 0.0004, -0.0761]
    extra_ee: [0, 0, 0.21, 0, 0, 0, 1]
    end_effector_points: [[0.,0.,0.]]
    
    # actions parameters 
    n_actions: 6
    
    # Reward parameters
    tgt_pose_indices: [0,1,2,3,4,5]
    distance_threshold: 5.0
    reward_type: 'distance'
    cost_positive: True
    cost:
        l1: 1.0
        l2: 10.0
        ws: [1.0,1.0,0.1]
        alpha: 0.00001